AllCops:
  Exclude: []

LineLength:
  Enabled: true
  Max: 80

Documentation:
  Enabled: false

AlignHash:
  Enabled: false

# Buggy cop:
EndOfLine:
  Enabled: false

AsciiComments:
  Enabled: false

TrivialAccessors:
  Enabled: false

PredicateName:
  Enabled: false

IndentationConsistency:
  Enabled: false

ConditionPosition:
  Enabled: false

IndentationWidth:
  Enabled: false

EndAlignment:
  Enabled: false

RegexpLiteral:
  Enabled: false
 
